### Create new article
POST http://localhost:3000/api/v1/articles
Content-Type: application/json

{
    "title": "Test Article",
    "description": "This is the content of article 1"
}

### Get all articles
GET http://localhost:3000/api/v1/articles

### Get article by id (replace :id with actual id)
GET http://localhost:3000/api/v1/articles/:id

### Update article (replace :id with actual id)
PUT http://localhost:3000/api/v1/articles/:id
Content-Type: application/json

{
    "title": "Updated Title",
    "description": "Updated Description"
}

### Delete article (replace :id with actual id)
DELETE http://localhost:3000/api/v1/articles/:id
